---

build:
  image: node:lts
  stage: build
  script:
    - yarn --no-progress --frozen-lockfile --cache-folder .yarn-cache/
    - yarn test
    - yarn build
  artifacts:
    paths:
      - dist/
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/

.deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -avz -e 'ssh -p2201' dist/ $SFTP_SERVER

deploy to development:
  extends: .deploy
  environment:
    name: development
  only:
    - master

deploy to production:
  extends: .deploy
  environment:
    name: production
  only:
    - tags
  when: manual
